### ISSUE TITLE
tern-jshint does not support Chinese text

### ISSUE THREAD

**Issue by hawkxu** [angelozerr/tern-jshint#2]
I write some jsdoc in Chinese, tern-jshint show all Chinese words as ?????

**Comment by angelozerr** [comment]
Never done that. Please share your sample. I don't know if tern can support Chinese character?

**Comment by hawkxu** [comment]
Oh, sorry, I think that is not tern-jshint issue, it may be tern issue.

**Comment by angelozerr** [comment]
> Oh, sorry, I think that is not tern-jshint issue, it may be tern issue.

@hawkxu I don't know, please share your sample in order to I see where encoding problem comes from.

**Comment by hawkxu** [comment]
I can not attach any file here. I put a simple test file at http://1drv.ms/1S8lfJ0

**Comment by angelozerr** [comment]
@hawkxu thanks for having shared your JavaScript file. 

> I can not attach any file here.

Next time, you can add it inside a github project or add it in the issue.

There is indeed a problem with Chinese character with tern.java. I have created the issue at https://github.com/angelozerr/tern.java/issues/364

**Comment by hawkxu** [comment]
Got it, thanks for your help.
