### ISSUE TITLE
.jshintrc support?

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-jshint#5]
I created a `.jshintrc` file in the project folder but it seems that it is not taken in count. Is it supported?

**Comment by PhaserEditor2D** [comment]
Yes, it is supported. The jshint options can be set in the `.tern-project` directly or set the `.jshintrc` path. This configuration `.tern-project` is working to me:

```
{
  "ecmaVersion": 6,
  "libs": [
    "browser",
    "ecma6"
  ],
  "plugins": {
    "doc_comment": {
      "strong": true
    },
    "outline": {

    },
    "jshint": {
        "config": {
      "unused": true
        }
    },
    "phaser": {

    }
  }
}
```

**Comment by angelozerr** [comment]
Yes it's again a feature that it is docummented. I must find time to do that.
