### ISSUE TITLE
tern-jshint used along with tern.java marks all problems as errors (even warnings)

### ISSUE THREAD

**Issue by orlandoibm** [angelozerr/tern-jshint#6]
Doing a deeper investigation, it seems that issue classification is done using an integer, while the actual values returned by jshint are strings.

Look here:
https://github.com/angelozerr/tern-jshint/blob/master/jshint.js#L224
## For example this jshint query:

``` json
{"query":{"type":"jshint","file":"app.js"},"files":[{"name":"app.js","text":"var http = require('http');\n\nvar port = (process.env.PORT || process.env.VCAP_APP_PORT || 8888);\n\nhttp.createServer(function (req, res) {\n\tres.writeHead(200, {'Content-Type': 'text/plain'});\n\tres.end('Hello World!\\n');\n}).listen(port);;\n\nconsole.log('Server running at http://127.0.0.1:'+port)\n\nconsole.log (\"Hola\");","type":"full"}]}
```

The tern result is:

``` json
{"messages":[{"message":"Unnecessary semicolon.","severity":"warning","from":235,"to":236,"file":"app.js"},{"message":"Missing semicolon.","severity":"error","from":293,"to":294,"file":"app.js"}]}
```

Looking at the "severity" field, those are strings ("warning", "error"), but the classification (switch) is done through numeric values (1, 2) which is causing this issue.

**Comment by angelozerr** [comment]
@orlandoibm I have fixed the problem. Now I use error.code of JSHint. If it starts with 'E', it's an error severiry, if it starts with 'W', it's a warning error. It's really better that my last code.

Thanks for having created this issue.
